### ISSUE TITLE
MaxMath Causes Much Longer Compile Times

### ISSUE THREAD

**Issue by virtushda** [MrUnbelievable92/MaxMath#15]
I used [Needles Compilation Visualizer](https://github.com/needle-tools/compilation-visualizer) to track compilation time in our project, I was hoping this could be addressed as it really cuts into productivity.

![image](https://user-images.githubusercontent.com/14203100/235372453-1a306456-1121-4ecc-a259-d4f0c39e4e85.png)

**Comment by MrUnbelievable92** [comment]
Okay so my initial guess would have been it _obviously_ being due to the source being 300k lines of source but then I saw that the MaxMath.Tests dll was compiled in a fraction of that time I wasn't sure so anymore, since its source is more than half of MaxMath itself in terms of lines of source.

I'm at a loss here and will have to investigate, but it doesn't seem to be a common issue.

**Comment by MrUnbelievable92** [comment]
Okay.
So first off, _on_ _my_ _machine_ ™ compilation of the `Tets.dll` also takes approximately 50% of the time it takes to compile the library itself. Strange.
The only compile time bottleneck I could think of was the use of `CallerMemberNameAttribute` in a function that's called 2049 times. Removing that decreased compilation time by about 10% (low sample size of tests lol so who knows).

I suspect it simply is related to the 300k lines of source.

May I ask why you frequently need to recompile every library? Because using an AssemblyDefinition has, as one of its benefits, the fact that changing your "game code" a.k.a. Assembly-CSharp.dll will not trigger recompilation of other assemblies.
Other than that I can only suggest removing unused functions. There's probably a ton of them and each has its own 1000+ line file somewhere within `Runtime\Math Lib\Functions`. Of course some other code might depend on it... It would be a painful process; a tool which knows about dependencies and which deletes source files (lol I guess) from within the editor would be a solution but only if the demand is there (i.e. I'd like to know what triggers recompiling all the time).

**Comment by MrUnbelievable92** [comment]
Assembly definitions address this issue; recompilation of this library is not triggered when writing/changing/deleting scripts not contained in either `MaxMath` or `CSharpDevTools`.
Until a reason for improving compilation time is provided, this is marked as invalid and subsequently closed.
