### ISSUE TITLE
Missing static factory methods like  var foo = byte4(x,y,z,w)

### ISSUE THREAD

**Issue by Neovariance** [MrUnbelievable92/MaxMath#3]
This is a silly issue but I'm used to using unity mathematics convention of doing 
float4 foo = float4(bar)
 instead of 
float4 foo = new float4(bar) 
and when I massively search and replace float4 by byte4, it doesn't compile and I have to use new byte4()

eg 
public static float4 float4(float x, float y, float z, float w) { return new float4(x, y, z, w); }

**Comment by MrUnbelievable92** [comment]
Originally didn't want to include them since it causes issues with other static methods of a type (for instance "quaternion.Euler") and the Unity.Mathematics team may remove them in the future [https://github.com/Unity-Technologies/Unity.Mathematics/issues/190](url).

I will add them in the next release (which has become huge - it might take another week), since those types don't have static methods apart from operators and such.

**Comment by Neovariance** [comment]
Thanks - it's better to stay coherent ( even when the design choices are not perfect ! ). 
Good to know that there is a huge next release coming !

**Comment by MrUnbelievable92** [comment]
Fixed in [Version 2.2.0](https://github.com/MrUnbelievable92/MaxMath/releases/tag/2.2.0)
